=== mathislucka/dualtext/dualtext_client/schemas/project_from_scratch.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ProjectFromScratch",
    "description": "Creating a project and everything else that is needed in one pass.",
    "type": "object",
    "properties": {
        "project": {
            "description": "The project that should be created.",
            "type": "object",
            "$ref": "project.schema.json"
        },
        "corpus": {
            "description": "A corpus that should be created with the project.",
            "type": "object",
            "$ref": "corpus.schema.json"
        },
        "labels": {
            "description": "Labels that should be created.",
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "label.schema.json"
            }
        },
        "annotations": {
            "description": "A list of annotations that should be created",
            "type": "array",
            "items": {
                "description": "An annotation item to be created",
                "type": "object",
                "properties": {
                    "identifier": {
                        "description": "A unique identifier used for assigning documents to this annotation.",
                        "type": "object",
                        "properties": {
                            "unique_id": ["string", "integer"],
                            "document_meta_key": "string"
                        }
                    },
                    "labels": {
                        "description": "A list of label names that should be assigned to this annotation.",
                        "type": "array",
                        "items": {
                            "type": "string"
                        }
                    },
                    "annotation_meta": {
                        "description": "Metadata for an annotation.",
                        "type": ["array", "object" ,"string"]
                    }
                }
            }
        },
        "documents": {
            "description": "A list of documents that should be created",
            "type": "array",
            "items": {
                "description": "A document that should be created.",
                "type": "object",
                "$ref": "document.schema.json"
            }
        },
        "annotation_groups": {
            "description": "A list of annotation groups that should be created",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "annotation_ids": {
                        "description": "The annotations that belong to this group.",
                        "type": "array",
                        "items": {
                            "type": "integer"
                        }
                    }
                }
            }
        }
    },
    "required": [ "project", "corpus", "annotations" ]
}

=== mathislucka/dualtext/dualtext_client/api_client/project_from_scratch_schema.json
{
    "project": {
        "name": "<project_name>"
    },
    "corpus": {
        "name": "<corpus_name>"
    },
    "labels": [
        { "name": "<label_name>" },
        { "name": "<label_name>" }
    ],
    "annotations": [
        {
            "documents": [ "<document_content>", "<document_content>" ]
        },
        {
            "documents": [ "<document_content>", "<document_content>" ]
        }
    ]
}
