=== mathislucka/dualtext/dualtext_client/schemas/project_from_documents.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "title": "ProjectFromSentences",
    "description": "Creating a project from a list of documents adding similar documents from an existing corpus.",
    "type": "object",
    "properties": {
        "project": {
            "description": "The project that should be created.",
            "type": "object",
            "$ref": "project.schema.json"
        },
        "labels": {
            "description": "Labels that should be created.",
            "type": "array",
            "items": {
                "type": "object",
                "$ref": "label.schema.json"
            }
        },
        "documents": {
            "description": "A list of documents that should be used to search candidates for the project to create.",
            "type": "array",
            "items": {
                "type": "object",
                "description": "A single document and how much this document should contribute to the total number of candidate documents.",
                "properties": {
                    "content": {
                        "type": "string"
                    },
                    "weight": {
                        "type": "number",
                        "exclusiveMinimum": 0,
                        "maximum": 1
                    }
                }
            }
        },
        "limit": {
            "description": "The maximum number of annotations that should be created.",
            "type": "integer"
        },
        "search_methods": {
            "description": "A list of methods that should be used to retrieve annotation candidates.",
            "type": "array",
            "items": {
                "type": "string"
            }
        }
    },
    "required": [ "project", "labels", "documents", "search_methods" ]
}

=== mathislucka/dualtext/dualtext_client/examples/create_from_search/create_from_search.json
{
    "project": {
        "name": "Search Project 4",
        "corpora": [1],
        "annotation_mode": "classification"
    },
    "labels": [
        { "name": "Sport", "key_code": "y" },
        { "name": "Not Sport", "key_code": "n" }
    ],
    "documents": [
        {
            "content": "Wenn künftig mehr Zuschauer zum Millerntor kommen sollten, dann wird der FC vielleicht einige amateurhafte Züge ablegen.",
            "weight": 0.5
        },
        {
            "content": "Damit hat die Mannschaft kaum noch Chancen auf den Einzug ins Viertelfinale der Weltmeisterschaft in Ägypten.",
            "weight": 0.5
        }
    ],
    "limit": 200,
    "search_methods": [ "sentence_embedding" ]
}
